version: '3.5'

services:
  redis:
    image: redis:3.2

  rails:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=preditores
      - POSTGRES_USERNAME=preditores
      - PIPEFY_GRAPHQL_ENDPOINT=https://app.pipefy.com/queries
      - RAILS_SKIP_ASSET_COMPILATION=false
      - RAILS_SKIP_MIGRATIONS=false
      - REDIS_URL=redis
      - DEVELOPMENT_CONSOLE_ALLOWED_IP=172.0.0.0/8
      - SENTRY_DSN=https://e8190f4eee4d4481a304a791da0e6121:100d5936252a4e9b8e630fb22879ecf1@sentry.hacklab.com.br/33
    ports:
      - 80:3000
    stdin_open: true
    tty: true

  postgres:
    image: postgres:9.6
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./compose/local/postgres_init_data:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=preditores
      - POSTGRES_USER=preditores
      - POSTGRES_PASSWORD=preditores
