version: '3.5'

services:
  redis:
    image: redis:3.2

  rails:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=preditores
      - POSTGRES_USERNAME=preditores
      - POSTGRES_PASSWORD=preditores
      # - BUNDLE_WITHOUT=test:development
      - DEVISE_SECRET_KEY=5618fa8ddd06b33eed7e8838bb693f2b22a3d7dcf47f201372a38cca809513b3a8faabfa0df0d1ddb1d0459a54c931c05f0b65abb3f787b88dc7a795f4cf4ccd
      - PIPEFY_GRAPHQL_ENDPOINT=https://app.pipefy.com/queries
      - PIPEFY_ORGANIZATION_ID=245636
      - PIPEFY_PIPE_TEMPLATE_ID=833479
      - PIPEFY_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyIjp7ImlkIjo0MTU0NDgsImVtYWlsIjoibGF1cnlAaGFja2xhYi5jb20uYnIiLCJhcHBsaWNhdGlvbiI6MzM5MjV9fQ.DQYkuH9XzcIyqIOi6cwHGCTgL0tRCxB8ee-wjZcmlns1dSPKqBKrdwJsK4UXZzFY8Tv4KvJNwV8xYTM_Xx6MOg
      - RAILS_SKIP_ASSET_COMPILATION=false
      - RAILS_SKIP_MIGRATIONS=false
      - SECRET_KEY_BASE=4dd4da4ff58133d33c6a8fee87202bdec22ef6d48c6a6a4ee51b0461433aef5f35fdc1f59149f2951bd2f043bf14e2aaddfea2b06bab86d70bee356dadc01ac9
      - REDIS_URL=redis
      - DEVELOPMENT_CONSOLE_ALLOWED_IP=192.168.0.0/16
    ports:
      - 80:3000
    stdin_open: true
    tty: true

  postgres:
    image: postgres:9.6
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./compose/local/postgres_init_data:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=preditores
      - POSTGRES_USER=preditores
      - POSTGRES_PASSWORD=preditores
