default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: predictors_system_development

test:
  <<: *default
  database: predictors_system_test

production:
  <<: *default
  database: predictors_system_production
  username: predictors_system
  password: <%= ENV['PREDICTORS_SYSTEM_DATABASE_PASSWORD'] %>
